terminate called after throwing an instance of 'std::runtime_error'
  what():  Unable to open file /home/yl182/zdd/Gitrepo/compilationRealizabilityWitnesses/2QBF2016/2QBF/floor256.qdimacs
/var/spool/slurm/job3377094/slurm_script: line 27: 12295 Aborted                 ${compilReal} ${specfile} > ${outfile}
