terminate called after throwing an instance of 'std::runtime_error'
  what():  Unable to open file /home/yl182/zdd/Gitrepo/compilationRealizabilityWitnesses/2QBF2016/2QBF/intermediate128.qdimacs
/var/spool/slurm/job3377095/slurm_script: line 27: 41442 Aborted                 ${compilReal} ${specfile} > ${outfile}
