terminate called after throwing an instance of 'std::runtime_error'
  what():  Unable to open file /home/yl182/zdd/Gitrepo/compilationRealizabilityWitnesses/2QBF2016/2QBF/ceiling256.qdimacs
/var/spool/slurm/job3377090/slurm_script: line 27: 12163 Aborted                 ${compilReal} ${specfile} > ${outfile}
